[tool.poetry]
name = "bot-cmder"
version = "0.1.0"
description = ""
authors = ["zonda yang <u226699@gmail.com>"]
readme = "README.md"
packages = [{include = "bot_cmder"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"
uvicorn = {extras = ["standard"], version = "^0.21.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
