"""`bot-cmder init` — first-run scaffold.

Creates `<config_dir>/app.yaml` (verbatim copy of the bundled example),
`<config_dir>/.env` (with a freshly generated `BOT_CMDER_MASTER_KEY`
and commented placeholders for adapter tokens), and `<state_dir>/`
(empty; first audit / TOTP write materializes the actual files).

Default destination follows the issue #20 search order — so on a
typical Linux/macOS box `bot-cmder init` populates
`~/.config/bot-cmder/` and `~/.local/state/bot-cmder/`. For source
contributors, `bot-cmder init --config-dir .` scaffolds the example
into the repo root instead.

Behavior on existing config:

  * default: refuse with exit 1 ("won't overwrite without --force")
  * --force: overwrite app.yaml + .env. The existing
    BOT_CMDER_MASTER_KEY is PRESERVED by default — losing TOTP
    enrollments because of a re-run is a footgun, so opting into
    that requires --rotate-key.
  * --rotate-key: regenerate the master key. Implies --force in
    spirit but still requires it explicitly so the destructive
    intent is unambiguous.
"""

from __future__ import annotations

import argparse
import sys
from importlib.resources import files
from pathlib import Path

from bot_cmder.config.paths import config_dir, state_dir

_ENV_TEMPLATE = """\
# bot-cmder secrets — generated by `bot-cmder init`.
# Anything in this file overrides the same-named field in app.yaml.
# Treat as you would a passwords vault: chmod 600, do NOT commit.

# Phase 2: Fernet symmetric key for the TOTP secret store. Lose this
# and every TOTP enrollment becomes unreadable; rotate this and every
# enrollment is invalidated. 32 url-safe base64 bytes.
BOT_CMDER_MASTER_KEY={master_key}

# --- Adapters (uncomment + fill the ones you actually use) ---

# Phase 1 — Telegram
# TELEGRAM_TOKEN=<from @BotFather>
# TELEGRAM_WEBHOOK_SECRET=<any long random string>
# TELEGRAM_MODE=webhook    # or "polling" for no-domain home labs

# Phase 4 — Discord (interactions mode needs all three)
# DISCORD_PUBLIC_KEY=<from Discord application General Information>
# DISCORD_BOT_TOKEN=<from Discord application Bot page>
# DISCORD_APPLICATION_ID=<numeric ID from URL>
# DISCORD_GUILD_ID=<dev guild ID for instant slash command propagation>
# DISCORD_MODE=interactions    # or "gateway" for no-domain home labs

# Phase 5 — Slack (events mode needs both; socket mode needs SLACK_APP_TOKEN)
# SLACK_SIGNING_SECRET=<from Basic Information → Signing Secret>
# SLACK_BOT_TOKEN=xoxb-...
# SLACK_APP_TOKEN=xapp-...    # only required when SLACK_MODE=socket
# SLACK_MODE=events            # or "socket" for no-domain home labs
"""


def _read_existing_master_key(env_path: Path) -> str | None:
    """Best-effort parse of `BOT_CMDER_MASTER_KEY=...` from an existing
    .env, so `--force` (without `--rotate-key`) preserves the key
    instead of regenerating it and silently breaking every existing
    TOTP enrollment.

    Delegates to `EnvFile.get` (issue #45) so there's ONE .env parser
    in the codebase. EnvFile handles all the edge cases (quoting,
    duplicate keys, comments interleaved with assignments) that the
    prior hand-rolled regex below missed.
    """
    from bot_cmder.cli._envfile import EnvFile

    if not env_path.is_file():
        return None
    return EnvFile.load(env_path).get("BOT_CMDER_MASTER_KEY")


def _generate_master_key() -> str:
    # Lazy import so `bot-cmder --help` doesn't pull cryptography.
    from cryptography.fernet import Fernet

    return Fernet.generate_key().decode()


def _resolve_config_dir(args: argparse.Namespace) -> Path:
    if args.config_dir is not None:
        return Path(args.config_dir).resolve()
    return config_dir()


def cmd_init(args: argparse.Namespace) -> int:
    cfg_dir = _resolve_config_dir(args)
    state = state_dir() if args.config_dir is None else (cfg_dir / "var").resolve()
    # When --config-dir is explicitly given, prefer a sibling `var/` so
    # `bot-cmder init --config-dir .` populates the repo's existing
    # ./var/ + ./config/ structure rather than scattering across CWD
    # and ~/.local/state.

    app_yaml = cfg_dir / "app.yaml"
    env_file = cfg_dir / ".env"

    if app_yaml.exists() and not args.force:
        print(
            f"bot-cmder init: refusing to overwrite {app_yaml}\n"
            f"  pass --force to replace (BOT_CMDER_MASTER_KEY in {env_file} "
            f"will be PRESERVED unless --rotate-key is also given).",
            file=sys.stderr,
        )
        return 1

    cfg_dir.mkdir(parents=True, exist_ok=True)
    state.mkdir(parents=True, exist_ok=True)

    template = files("bot_cmder.data").joinpath("app.yaml.example").read_text(encoding="utf-8")
    app_yaml.write_text(template, encoding="utf-8")

    if args.rotate_key:
        master_key = _generate_master_key()
        rotated_note = " (rotated — existing TOTP enrollments are now invalid)"
    else:
        existing = _read_existing_master_key(env_file)
        master_key = existing or _generate_master_key()
        rotated_note = " (preserved existing key)" if existing else ""

    env_file.write_text(_ENV_TEMPLATE.format(master_key=master_key), encoding="utf-8")
    # Tighten perms — .env contains the master key. 600 = owner rw only.
    env_file.chmod(0o600)

    print(f"Created {app_yaml} (edit users + ACL before serve)")
    print(f"Created {env_file} (contains BOT_CMDER_MASTER_KEY — back this up{rotated_note})")
    print(f"Created {state}/")
    print()
    print("Next steps:")
    print("  bot-cmder configure                          # walk through adapter credentials interactively")
    print("  bot-cmder enroll-totp --user telegram:<your-id>")
    print("  bot-cmder serve")
    return 0


def add_subparsers(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "init",
        help="Scaffold app.yaml + .env + state dir for first-time setup",
        description=(
            "Create a fresh app.yaml + .env (with a freshly generated "
            "BOT_CMDER_MASTER_KEY) at the XDG config location, and mkdir -p "
            "the state directory. Pass --config-dir . to scaffold into the "
            "current repo (source contributor flow)."
        ),
    )
    p.add_argument(
        "--config-dir",
        default=None,
        help=(
            "Override the destination directory. Default: $XDG_CONFIG_HOME/bot-cmder/ "
            "(typically ~/.config/bot-cmder/)."
        ),
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing app.yaml + .env. Master key is preserved unless --rotate-key.",
    )
    p.add_argument(
        "--rotate-key",
        action="store_true",
        help=(
            "When combined with --force, regenerate BOT_CMDER_MASTER_KEY. "
            "DESTRUCTIVE: invalidates every existing TOTP enrollment."
        ),
    )
    p.set_defaults(func=cmd_init)
